# Generated by Django 3.0.5 on 2020-05-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200430_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'My subscriber', 'verbose_name_plural': 'My subscribers'},
        ),
    ]
