# Generated by Django 3.0.5 on 2020-05-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200503_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsinorder',
            options={'verbose_name': 'Product in order', 'verbose_name_plural': 'Products in order'},
        ),
    ]
