# Generated by Django 3.0.5 on 2020-05-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200507_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
